### ISSUE TITLE
Query if a lockId is released or not

### ISSUE THREAD

**Issue by anshul-kai** [FinalZJY/SharedMemory#4]
No way to query if a lockId was released or not. `releaseLock` always returns OK.

**Comment by FinalZJY** [comment]
1. Usually, you dont't need to query if a lockId was released or not. You should call `releaseLock` immediately after your operations of an object if you call `getLock` first, which means you should not hold a lock for a long time. These two functions are a pair.
2. The return value of `releaseLock` is always 'OK' yet. I'll change the return value in the next version if the lockId does not match the object's lockId.

**Comment by anshul-kai** [comment]
I agree that my use case is somewhat unique but it seemed like a reasonable ask. Thanks for taking care of it.
